### ISSUE TITLE
Documentation request around expression evulator package

### ISSUE THREAD

**Issue by DhruvBarot** [neuroglia-io/framework#110]
Hello, I was trying to understand an expression evaluator package that is used in Synapse for serverless workflow, If I wanted to use the same package for some different project I could not find any documentation about how to use it.

If can build a wiki around the packages then it will be helpful for others to consume independently. 

I can understand there is lot of work on creating an documentation around this, if could build samples around those then it will be very helpful for other to consume and understand.

**Comment by cdavernas** [comment]
@DhruvBarot yes, indeed, documenting all packages is gonna take a while, especially that I've got a lot on my plate at the moment, as usual 😆 

However, is there something specific I can help you with for the time being?

**Comment by cdavernas** [comment]
@DhruvBarot I just added a README for both JS and JQ expression evaluators, thus addressing this issue. Don't hesitate to ask if you need any help 😉
