### ISSUE TITLE
Be more explicit when a background service is missing.

### ISSUE THREAD

**Issue by JBBianchi** [neuroglia-io/framework#27]
When testing an implementation using the CloudEventBus, a null ref exception was throw. 

[Queue](https://github.com/neuroglia-io/framework/blob/main/src/Eventing/Neuroglia.Eventing.CloudEvents/Services/CloudEventBus.cs#L129) appeared to be null because the background service wasn't provided by the host.

A more explicit error should be displayed throw instead of the null ref.

**Comment by cdavernas** [comment]
Closed as stale
