### ISSUE TITLE
Reducer vs Feature in Flux

### ISSUE THREAD

**Issue by JBBianchi** [neuroglia-io/framework#28]
If a `Feature` has no `Reducer`, it won't be created and it's access will fail. Either allow feature without reducer or log a warning in `Neuroglia.Data.Flux`

**Comment by cdavernas** [comment]
@JBBianchi I think both are necessary actually: we could very well have a reducerless state using effects only, for example. The warning is necessary if that was not intended, or if reducers were defined were improperly defined as non-public and/or non-static.

**Comment by cdavernas** [comment]
Closed as stale
