### ISSUE TITLE
Redundancy between ArgumentMustBeHigherOrLowerThan and ArgumentMustBeLowerOrHigherThan

### ISSUE THREAD

**Issue by 0nary** [neuroglia-io/framework#29]
I think they are a redundancy between [ArgumentMustBeHigherOrLowerThan ](https://github.com/neuroglia-io/framework/blob/main/src/Data/Neuroglia.Data/DomainException.cs#L208) and [ArgumentMustBeLowerOrHigherThan](https://github.com/neuroglia-io/framework/blob/main/src/Data/Neuroglia.Data/DomainException.cs#L241) in Data DomainException.

ArgumentMustBeLowerOrHigherThan should drop because he exists only for int.

**Comment by cdavernas** [comment]
Closed as stale
