### ISSUE TITLE
Test Data.Repositories run endlessly

### ISSUE THREAD

**Issue by 0nary** [neuroglia-io/framework#39]
**Describe the bug**
When Test Data.Repositories are run in the test workflows the step run endlessly.

**Expected behavior**
I expected the Test Data.Repositories to run, then return the test result.

**Additional context**
If we remove `.UntilCommandIsCompleted($"mongo {MongoDBContainer.DefaultDatabase}")` from the [MongoDBContainerBuilder](https://github.com/neuroglia-io/framework/blob/fbf94aceeee612bca2907baf5763c68d9777cd77/test/Neuroglia.UnitTests/Containers/MongoDBContainerBuilder.cs#L25)
and we replace :
```
- name: Test Data.Repositories
        run: dotnet test "${{ env.SOLUTION }}" --no-restore --verbosity normal --filter "FullyQualifiedName~Data.Repositories"
      
```
By
```
- name: Test Data.Repositories.DistributedCacheRepositoryTests
        run: dotnet test "${{ env.SOLUTION }}" --no-restore --verbosity normal --filter "FullyQualifiedName~Data.Repositories.DistributedCacheRepositoryTests"
      - name: Test Data.Repositories.EFCoreRepositoryTests
        run: dotnet test "${{ env.SOLUTION }}" --no-restore --verbosity normal --filter "FullyQualifiedName~Data.Repositories.EFCoreRepositoryTests"
      - name: Test Data.Repositories.EventSourcingRepositoryTests
        run: dotnet test "${{ env.SOLUTION }}" --no-restore --verbosity normal --filter "FullyQualifiedName~Data.Repositories.EventSourcingRepositoryTests"
      - name: Test Data.Repositories.MongoRepositoryTests
        run: dotnet test "${{ env.SOLUTION }}" --no-restore --verbosity normal --filter "FullyQualifiedName~Data.Repositories.MongoRepositoryTests"
```
The tests run 'properly'.

**Comment by 0nary** [comment]
When I try to run EventSourcingRepositoryTests or EFCoreRepositoryTests with any other Repositories test, the step will run endlessly in the test workflow.

**Comment by cdavernas** [comment]
Closed as stale
