### ISSUE TITLE
Add static method ArgumentMustBeEarlierThan how will take DateTime and DateTimeOffset

### ISSUE THREAD

**Issue by 0nary** [neuroglia-io/framework#9]
Currently, in DomainException, they have only a method ArgumentMustBeEarlierThan how take only TimeSpan, it will be nice to have one how can take DateTime and one how take DateTimeOffset.
It will be also nice to have a ArgumentMustBeLaterThan how can take DateTimeOffset (currently only TimeSpan and DateTime).

**Comment by cdavernas** [comment]
Closed as stale
